apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nginx-sts.fullname" . }}
  labels:
    {{- include "nginx-sts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "nginx-sts.fullname" . }}-service
  selector:
    matchLabels:
      app: {{ include "nginx-sts.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nginx-sts.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
  volumeClaimTemplates:
  - metadata:
      name: nginx-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.persistence.size }}

